markdown: kramdown
rouge: rouge

# 作者信息
author:
  name: Elirc Hou
  email: kaqijiang@gmail.com
  # link: http://github.com/kaqijiang
  # weibo: http://github.com/kaqijiang
  github: http://github.com/kaqijiang

# 站点信息
title: J Blog
description: J的博客
# url: http://github.com/kaqijiang
language: 中文

exclude: ['vendor', 'README.md', 'Gemfile', 'Gemfile.lock', 'config.ru', 'unicorn.rb', 'Procfile']
 